spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Kiev&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081

---
spring:
  profiles: sachukDBlocalhost
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/Vstup_2021?characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Kiev&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
